# Generated by Django 6.0.3 on 2026-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('interaction_score', models.IntegerField()),
                ('company_size', models.IntegerField()),
                ('status', models.CharField(default='New', max_length=20)),
                ('lead_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
