# Generated by Django 6.0.3 on 2026-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Hot', 'Hot Lead'), ('Warm', 'Warm Lead'), ('Cold', 'Cold Lead'), ('New', 'New Lead')], default='New', max_length=10),
        ),
    ]
