# Generated by Django 6.0.3 on 2026-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_crm_status_alter_lead_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interaction_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='crm_status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
